### ISSUE TITLE
[BUG] AssertionError with Zero3 defragmentation (tensors on multiple devices)

### ISSUE THREAD

**Issue by tgaddair** [microsoft/DeepSpeed#3561]
**Describe the bug**
When using zero stage 3 with optimizer offload to CPU, and error occurs during defragmentation where tensors are expected to all be on the same device. Here's an example stack trace:

```
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ludwig/distributed/deepspeed.py", line 99, in prepare
    model_engine, optimizer, _, _ = deepspeed.initialize(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 308, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1173, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1463, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 256, in __init__
    self._create_fp16_partitions_with_defragmentation(self.trainable_param_groups)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 600, in _create_fp16_partitions_with_defragmentation
    device_buffer = __class__.defragment(parameter_partitions)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 436, in defragment
    assert len(set(t.device for t in tensors)) == 1
AssertionError
```

This is also the same issue reported in the Dolly repo: https://github.com/databrickslabs/dolly/issues/125

The workaround was to downgrade to `deepspeed<0.9`, which resolves the issue, but also means I'm stuck using an older version of deepspeed.

**To Reproduce**
See https://github.com/databrickslabs/dolly/issues/125

**Expected behavior**
Initialization should succeed.

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/ray/anaconda3/lib/python3.8/site-packages/torch']
torch version .................... 2.0.0+cu118
deepspeed install path ........... ['/home/ray/anaconda3/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.9.2, unknown, unknown
torch cuda version ............... 11.8
torch hip version ................ None
nvcc version ..................... 11.8
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.8
```

**Screenshots**
N/A

**System info (please complete the following information):**
 - OS: Ubuntu 22.04
 - 1 machine with 4x A5000 GPUs
 - N/A
 - 3.8

**Launcher context**
This is using `torchrun`.

**Docker context**
`nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04`

**Additional context**
N/A

**Comment by qingqiuhe** [comment]
same error

**Comment by jomayeri** [comment]
Hi @tgaddair could you try cloning the latest version of DeepSpeed. It contains [this commit](https://github.com/microsoft/DeepSpeed/pull/3420) which has been associated with the error you posted.

**Comment by tgaddair** [comment]
Hi @jomayeri, thanks for following up. We confirmed this issue is fixed with the latest master.

**Comment by seongminp** [comment]
Hmm.. I am still getting the same error on 0.9.4. Is anyone else experiencing the same thing?

**Comment by tomaslaz** [comment]
I am getting the same error using 0.9.3.

**Comment by jomayeri** [comment]
@tomaslaz @seongminp Please open a new issue with your stacktrace, repro script, and all the request information.
