### ISSUE TITLE
[BUG] AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam' for multinode training

### ISSUE THREAD

**Issue by larrylawl** [microsoft/DeepSpeed#3969]
**Describe the bug**
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam' for multinode training

**To Reproduce**

To reproduce, run the following with your `hostfile` and `deepspeed` config specified. I used the zero3 config [here](https://huggingface.co/docs/transformers/main_classes/deepspeed#zero3-config).

```
deepspeed --hostfile=$PBS_O_WORKDIR/hostfile $ROOT_DIR/transformers/examples/pytorch/language-modeling/run_clm.py \
    --model_name_or_path gpt2 \
    --dataset_name wikitext \
    --dataset_config_name wikitext-2-raw-v1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --do_train \
    --do_eval \
    --output_dir ~/scratch/finetuned_models/debug \
    --deepspeed "$ROOT_DIR/FastChat/fastchat/ds_config/ds_config_zero3.json"
```

I ran into the error `AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'`. Here's the (truncated) logs:

```
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/opt/cray/pe/cce/13.0.2/cce/aarch64/lib/libcray-c++-rts.a')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/opt/cray/pe/cti/2.15.10/lib/pkgconfig')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/opt/cray/pe/cce/13.0.2/cce/aarch64/lib')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/opt/cray/pe/cce/13.0.2/cce/x86_64/share/nls/En/%N.cat')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/opt/cray/pe/mpich/8.1.15/ofi/@PRGENV@/@PE_MPICH_GENCOMPS@/lib/pkgconfig')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('libfabric/1.11.0.4.125'), PosixPath('cray-pals/1.1.6'), PosixPath('craype-x86-rome'), PosixPath('craype-network-ofi'), PosixPath('cce/13.0.2'), PosixPath('cray-dsmml/0.2.2'), PosixPath('perftools-base/22.04.0'), PosixPath('cray-mpich/8.1.15'), PosixPath('craype/2.7.15'), PosixPath('PrgEnv-cray/8.3.3')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/opt/cray/pe/cce/13.0.2/cce/aarch64/include/craylibs')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/opt/gcc-cross-aarch64/8.1.0/aarch64')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/opt/cray/pe/fftw/3.3.8.13/@PE_FFTW_DEFAULT_TARGET@/lib/pkgconfig')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/opt/cray/pe/libsci/21.08.1.2/@PRGENV@/@PE_LIBSCI_DEFAULT_GENCOMPS@/@PE_LIBSCI_DEFAULT_TARGET@/lib/pkgconfig')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/opt/cray/pe/sma/11.5.3.beta/ofi/sma@PE_SMA_DEFAULT_DIR_DEFAULT64@/lib64/pkgconfig')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/opt/clmgr/man'), PosixPath('/opt/cray/pe/man')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/opt/modulefiles')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('libexec64/opts')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: CUDA SETUP: Highest compute capability among GPUs detected: 8.0
x1000c1s1b0n0: CUDA SETUP: Detected CUDA version 116
x1000c1s1b0n0: CUDA SETUP: Loading binary /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('() {  eval `/opt/cray/pe/modules/3.2.11.6/bin/modulecmd bash $*`\n}')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
x1000c1s1b0n0:   warn(msg)
x1000c1s1b0n0: [2023-07-16 11:23:41,585] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
x1000c1s1b0n0: [2023-07-16 11:23:41,586] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
x1000c0s6b0n0: [2023-07-16 11:23:44,841] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
x1000c0s6b0n0: [2023-07-16 11:23:44,841] [INFO] [comm.py:594:init_distributed] cdb=None
x1000c0s6b0n0: [2023-07-16 11:23:44,841] [INFO] [comm.py:625:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
x1000c0s6b0n0: [2023-07-16 11:23:44,842] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
x1000c0s6b0n0: [2023-07-16 11:23:44,842] [INFO] [comm.py:594:init_distributed] cdb=None
x1000c1s1b0n0: [2023-07-16 11:23:46,769] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
x1000c1s1b0n0: [2023-07-16 11:23:46,770] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
x1000c1s1b0n0: [2023-07-16 11:23:46,770] [INFO] [comm.py:594:init_distributed] cdb=None
x1000c1s1b0n0: [2023-07-16 11:23:46,770] [INFO] [comm.py:594:init_distributed] cdb=None
x1000c0s6b0n0: 07/16/2023 11:23:47 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: False
x1000c0s6b0n0: 07/16/2023 11:23:47 - INFO - __main__ - Training/evaluation parameters TrainingArguments(
x1000c0s6b0n0: _n_gpu=1,
x1000c0s6b0n0: adafactor=False,
x1000c0s6b0n0: adam_beta1=0.9,
x1000c0s6b0n0: adam_beta2=0.999,
x1000c0s6b0n0: adam_epsilon=1e-08,
x1000c0s6b0n0: auto_find_batch_size=False,
x1000c0s6b0n0: bf16=False,
x1000c0s6b0n0: bf16_full_eval=False,
x1000c0s6b0n0: data_seed=None,
x1000c0s6b0n0: dataloader_drop_last=False,
x1000c0s6b0n0: dataloader_num_workers=0,
x1000c0s6b0n0: dataloader_pin_memory=True,
x1000c0s6b0n0: ddp_backend=None,
x1000c0s6b0n0: ddp_broadcast_buffers=None,
x1000c0s6b0n0: ddp_bucket_cap_mb=None,
x1000c0s6b0n0: ddp_find_unused_parameters=None,
x1000c0s6b0n0: ddp_timeout=1800,
x1000c0s6b0n0: debug=[],
x1000c0s6b0n0: deepspeed=/home/users/industry/dso/lannliat/FastChat/fastchat/ds_config/ds_config_zero3.json,
x1000c0s6b0n0: disable_tqdm=False,
x1000c0s6b0n0: do_eval=True,
x1000c0s6b0n0: do_predict=False,
x1000c0s6b0n0: do_train=True,
x1000c0s6b0n0: eval_accumulation_steps=None,
x1000c0s6b0n0: eval_delay=0,
x1000c0s6b0n0: eval_steps=None,
x1000c0s6b0n0: evaluation_strategy=no,
x1000c0s6b0n0: fp16=False,
x1000c0s6b0n0: fp16_backend=auto,
x1000c0s6b0n0: fp16_full_eval=False,
x1000c0s6b0n0: fp16_opt_level=O1,
x1000c0s6b0n0: fsdp=[],
x1000c0s6b0n0: fsdp_config={'fsdp_min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
x1000c0s6b0n0: fsdp_min_num_params=0,
x1000c0s6b0n0: fsdp_transformer_layer_cls_to_wrap=None,
x1000c0s6b0n0: full_determinism=False,
x1000c0s6b0n0: gradient_accumulation_steps=1,
x1000c0s6b0n0: gradient_checkpointing=False,
x1000c0s6b0n0: greater_is_better=None,
x1000c0s6b0n0: group_by_length=False,
x1000c0s6b0n0: half_precision_backend=auto,
x1000c0s6b0n0: hub_model_id=None,
x1000c0s6b0n0: hub_private_repo=False,
x1000c0s6b0n0: hub_strategy=every_save,
x1000c0s6b0n0: hub_token=<HUB_TOKEN>,
x1000c0s6b0n0: ignore_data_skip=False,
x1000c0s6b0n0: include_inputs_for_metrics=False,
x1000c0s6b0n0: jit_mode_eval=False,
x1000c0s6b0n0: label_names=None,
x1000c0s6b0n0: label_smoothing_factor=0.0,
x1000c0s6b0n0: learning_rate=5e-05,
x1000c0s6b0n0: length_column_name=length,
x1000c0s6b0n0: load_best_model_at_end=False,
x1000c0s6b0n0: local_rank=0,
x1000c0s6b0n0: log_level=passive,
x1000c0s6b0n0: log_level_replica=warning,
x1000c0s6b0n0: log_on_each_node=True,
x1000c0s6b0n0: logging_dir=/home/users/industry/dso/lannliat/scratch/finetuned_models/debug/runs/Jul16_11-23-44_x1000c0s6b0n0,
x1000c0s6b0n0: logging_first_step=False,
x1000c0s6b0n0: logging_nan_inf_filter=True,
x1000c0s6b0n0: logging_steps=500,
x1000c0s6b0n0: logging_strategy=steps,
x1000c0s6b0n0: lr_scheduler_type=linear,
x1000c0s6b0n0: max_grad_norm=1.0,
x1000c0s6b0n0: max_steps=-1,
x1000c0s6b0n0: metric_for_best_model=None,
x1000c0s6b0n0: mp_parameters=,
x1000c0s6b0n0: no_cuda=False,
x1000c0s6b0n0: num_train_epochs=3.0,
x1000c0s6b0n0: optim=adamw_hf,
x1000c0s6b0n0: optim_args=None,
x1000c0s6b0n0: output_dir=/home/users/industry/dso/lannliat/scratch/finetuned_models/debug,
x1000c0s6b0n0: overwrite_output_dir=False,
x1000c0s6b0n0: past_index=-1,
x1000c0s6b0n0: per_device_eval_batch_size=8,
x1000c0s6b0n0: per_device_train_batch_size=8,
x1000c0s6b0n0: prediction_loss_only=False,
x1000c0s6b0n0: push_to_hub=False,
x1000c0s6b0n0: push_to_hub_model_id=None,
x1000c0s6b0n0: push_to_hub_organization=None,
x1000c0s6b0n0: push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
x1000c0s6b0n0: ray_scope=last,
x1000c0s6b0n0: remove_unused_columns=True,
x1000c0s6b0n0: report_to=['wandb'],
x1000c0s6b0n0: resume_from_checkpoint=None,
x1000c0s6b0n0: run_name=/home/users/industry/dso/lannliat/scratch/finetuned_models/debug,
x1000c0s6b0n0: save_on_each_node=False,
x1000c0s6b0n0: save_safetensors=False,
x1000c0s6b0n0: save_steps=500,
x1000c0s6b0n0: save_strategy=steps,
x1000c0s6b0n0: save_total_limit=None,
x1000c0s6b0n0: seed=42,
x1000c0s6b0n0: sharded_ddp=[],
x1000c0s6b0n0: skip_memory_metrics=True,
x1000c0s6b0n0: tf32=None,
x1000c0s6b0n0: torch_compile=False,
x1000c0s6b0n0: torch_compile_backend=None,
x1000c0s6b0n0: torch_compile_mode=None,
x1000c0s6b0n0: torchdynamo=None,
x1000c0s6b0n0: tpu_metrics_debug=False,
x1000c0s6b0n0: tpu_num_cores=None,
x1000c0s6b0n0: use_ipex=False,
x1000c0s6b0n0: use_legacy_prediction_loop=False,
x1000c0s6b0n0: use_mps_device=False,
x1000c0s6b0n0: warmup_ratio=0.0,
x1000c0s6b0n0: warmup_steps=0,
x1000c0s6b0n0: weight_decay=0.0,
x1000c0s6b0n0: xpu_backend=None,
x1000c0s6b0n0: )
x1000c0s6b0n0: 07/16/2023 11:23:47 - WARNING - __main__ - Process rank: 1, device: cuda:1, n_gpu: 1distributed training: True, 16-bits training: False
x1000c1s1b0n0: 07/16/2023 11:23:47 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: False
x1000c1s1b0n0: 07/16/2023 11:23:47 - INFO - __main__ - Training/evaluation parameters TrainingArguments(
x1000c1s1b0n0: _n_gpu=1,
x1000c1s1b0n0: adafactor=False,
x1000c1s1b0n0: adam_beta1=0.9,
x1000c1s1b0n0: adam_beta2=0.999,
x1000c1s1b0n0: adam_epsilon=1e-08,
x1000c1s1b0n0: auto_find_batch_size=False,
x1000c1s1b0n0: bf16=False,
x1000c1s1b0n0: bf16_full_eval=False,
x1000c1s1b0n0: data_seed=None,
x1000c1s1b0n0: dataloader_drop_last=False,
x1000c1s1b0n0: dataloader_num_workers=0,
x1000c1s1b0n0: dataloader_pin_memory=True,
x1000c1s1b0n0: ddp_backend=None,
x1000c1s1b0n0: ddp_broadcast_buffers=None,
x1000c1s1b0n0: ddp_bucket_cap_mb=None,
x1000c1s1b0n0: ddp_find_unused_parameters=None,
x1000c1s1b0n0: ddp_timeout=1800,
x1000c1s1b0n0: debug=[],
x1000c1s1b0n0: deepspeed=/home/users/industry/dso/lannliat/FastChat/fastchat/ds_config/ds_config_zero3.json,
x1000c1s1b0n0: disable_tqdm=False,
x1000c1s1b0n0: do_eval=True,
x1000c1s1b0n0: do_predict=False,
x1000c1s1b0n0: do_train=True,
x1000c1s1b0n0: eval_accumulation_steps=None,
x1000c1s1b0n0: eval_delay=0,
x1000c1s1b0n0: eval_steps=None,
x1000c1s1b0n0: evaluation_strategy=no,
x1000c1s1b0n0: fp16=False,
x1000c1s1b0n0: fp16_backend=auto,
x1000c1s1b0n0: fp16_full_eval=False,
x1000c1s1b0n0: fp16_opt_level=O1,
x1000c1s1b0n0: fsdp=[],
x1000c1s1b0n0: fsdp_config={'fsdp_min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
x1000c1s1b0n0: fsdp_min_num_params=0,
x1000c1s1b0n0: fsdp_transformer_layer_cls_to_wrap=None,
x1000c1s1b0n0: full_determinism=False,
x1000c1s1b0n0: gradient_accumulation_steps=1,
x1000c1s1b0n0: gradient_checkpointing=False,
x1000c1s1b0n0: greater_is_better=None,
x1000c1s1b0n0: group_by_length=False,
x1000c1s1b0n0: half_precision_backend=auto,
x1000c1s1b0n0: hub_model_id=None,
x1000c1s1b0n0: hub_private_repo=False,
x1000c1s1b0n0: hub_strategy=every_save,
x1000c1s1b0n0: hub_token=<HUB_TOKEN>,
x1000c1s1b0n0: ignore_data_skip=False,
x1000c1s1b0n0: include_inputs_for_metrics=False,
x1000c1s1b0n0: jit_mode_eval=False,
x1000c1s1b0n0: label_names=None,
x1000c1s1b0n0: label_smoothing_factor=0.0,
x1000c1s1b0n0: learning_rate=5e-05,
x1000c1s1b0n0: length_column_name=length,
x1000c1s1b0n0: load_best_model_at_end=False,
x1000c1s1b0n0: local_rank=0,
x1000c1s1b0n0: log_level=passive,
x1000c1s1b0n0: log_level_replica=warning,
x1000c1s1b0n0: log_on_each_node=True,
x1000c1s1b0n0: logging_dir=/home/users/industry/dso/lannliat/scratch/finetuned_models/debug/runs/Jul16_11-23-46_x1000c1s1b0n0,
x1000c1s1b0n0: logging_first_step=False,
x1000c1s1b0n0: logging_nan_inf_filter=True,
x1000c1s1b0n0: logging_steps=500,
x1000c1s1b0n0: logging_strategy=steps,
x1000c1s1b0n0: lr_scheduler_type=linear,
x1000c1s1b0n0: max_grad_norm=1.0,
x1000c1s1b0n0: max_steps=-1,
x1000c1s1b0n0: metric_for_best_model=None,
x1000c1s1b0n0: mp_parameters=,
x1000c1s1b0n0: no_cuda=False,
x1000c1s1b0n0: num_train_epochs=3.0,
x1000c1s1b0n0: optim=adamw_hf,
x1000c1s1b0n0: optim_args=None,
x1000c1s1b0n0: output_dir=/home/users/industry/dso/lannliat/scratch/finetuned_models/debug,
x1000c1s1b0n0: overwrite_output_dir=False,
x1000c1s1b0n0: past_index=-1,
x1000c1s1b0n0: per_device_eval_batch_size=8,
x1000c1s1b0n0: per_device_train_batch_size=8,
x1000c1s1b0n0: prediction_loss_only=False,
x1000c1s1b0n0: push_to_hub=False,
x1000c1s1b0n0: push_to_hub_model_id=None,
x1000c1s1b0n0: push_to_hub_organization=None,
x1000c1s1b0n0: push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
x1000c1s1b0n0: ray_scope=last,
x1000c1s1b0n0: remove_unused_columns=True,
x1000c1s1b0n0: report_to=['wandb'],
x1000c1s1b0n0: resume_from_checkpoint=None,
x1000c1s1b0n0: run_name=/home/users/industry/dso/lannliat/scratch/finetuned_models/debug,
x1000c1s1b0n0: save_on_each_node=False,
x1000c1s1b0n0: save_safetensors=False,
x1000c1s1b0n0: save_steps=500,
x1000c1s1b0n0: save_strategy=steps,
x1000c1s1b0n0: save_total_limit=None,
x1000c1s1b0n0: seed=42,
x1000c1s1b0n0: sharded_ddp=[],
x1000c1s1b0n0: skip_memory_metrics=True,
x1000c1s1b0n0: tf32=None,
x1000c1s1b0n0: torch_compile=False,
x1000c1s1b0n0: torch_compile_backend=None,
x1000c1s1b0n0: torch_compile_mode=None,
x1000c1s1b0n0: torchdynamo=None,
x1000c1s1b0n0: tpu_metrics_debug=False,
x1000c1s1b0n0: tpu_num_cores=None,
x1000c1s1b0n0: use_ipex=False,
x1000c1s1b0n0: use_legacy_prediction_loop=False,
x1000c1s1b0n0: use_mps_device=False,
x1000c1s1b0n0: warmup_ratio=0.0,
x1000c1s1b0n0: warmup_steps=0,
x1000c1s1b0n0: weight_decay=0.0,
x1000c1s1b0n0: xpu_backend=None,
x1000c1s1b0n0: )
x1000c1s1b0n0: 07/16/2023 11:23:47 - WARNING - __main__ - Process rank: 1, device: cuda:1, n_gpu: 1distributed training: True, 16-bits training: False
...
x1000c0s6b0n0: [2023-07-16 11:24:01,734] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.9.5, git-hash=unknown, git-branch=unknown
x1000c0s6b0n0: [2023-07-16 11:24:02,277] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
x1000c0s6b0n0:  [WARNING]  cpu_adam cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!
x1000c0s6b0n0: Using /home/users/industry/dso/lannliat/.cache/torch_extensions/py310_cu116 as PyTorch extensions root...
x1000c1s1b0n0:  [WARNING]  cpu_adam cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!
x1000c1s1b0n0: Using /home/users/industry/dso/lannliat/.cache/torch_extensions/py310_cu116 as PyTorch extensions root...
x1000c1s1b0n0:  [WARNING]  cpu_adam cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!
x1000c1s1b0n0: Using /home/users/industry/dso/lannliat/.cache/torch_extensions/py310_cu116 as PyTorch extensions root...
x1000c1s1b0n0: Traceback (most recent call last):
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/transformers/examples/pytorch/language-modeling/run_clm.py", line 634, in <module>
x1000c1s1b0n0:     main()
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/transformers/examples/pytorch/language-modeling/run_clm.py", line 582, in main
x1000c1s1b0n0:     train_result = trainer.train(resume_from_checkpoint=checkpoint)
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/transformers/src/transformers/trainer.py", line 1539, in train
x1000c1s1b0n0:     return inner_training_loop(
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/transformers/src/transformers/trainer.py", line 1659, in _inner_training_loop
x1000c1s1b0n0:     model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/accelerate/accelerator.py", line 1198, in prepare
x1000c1s1b0n0:     result = self._prepare_deepspeed(*args)
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/accelerate/accelerator.py", line 1537, in _prepare_deepspeed
x1000c1s1b0n0:     engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/__init__.py", line 165, in initialize
x1000c1s1b0n0:     engine = DeepSpeedEngine(args=args,
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 309, in __init__
x1000c1s1b0n0:     self._configure_optimizer(optimizer, model_parameters)
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1173, in _configure_optimizer
x1000c1s1b0n0:     basic_optimizer = self._configure_basic_optimizer(model_parameters)
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1229, in _configure_basic_optimizer
x1000c1s1b0n0:     optimizer = DeepSpeedCPUAdam(model_parameters,
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
x1000c1s1b0n0:     self.ds_opt_adam = CPUAdamBuilder().load()
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 454, in load
x1000c1s1b0n0:     return self.jit_load(verbose)
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 497, in jit_load
x1000c1s1b0n0:     op_module = load(name=self.name,
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
x1000c1s1b0n0:     return _jit_compile(
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
x1000c1s1b0n0:     _write_ninja_file_and_build_library(
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1592, in _write_ninja_file_and_build_library
x1000c1s1b0n0:     verify_ninja_availability()
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1648, in verify_ninja_availability
x1000c1s1b0n0:     raise RuntimeError("Ninja is required to load C++ extensions")
x1000c1s1b0n0: RuntimeError: Ninja is required to load C++ extensions
x1000c0s6b0n0: Traceback (most recent call last):
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/transformers/examples/pytorch/language-modeling/run_clm.py", line 634, in <module>
x1000c0s6b0n0:     main()
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/transformers/examples/pytorch/language-modeling/run_clm.py", line 582, in main
x1000c0s6b0n0:     train_result = trainer.train(resume_from_checkpoint=checkpoint)
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/transformers/src/transformers/trainer.py", line 1539, in train
x1000c0s6b0n0:     return inner_training_loop(
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/transformers/src/transformers/trainer.py", line 1659, in _inner_training_loop
x1000c0s6b0n0:     model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/accelerate/accelerator.py", line 1198, in prepare
x1000c0s6b0n0:     result = self._prepare_deepspeed(*args)
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/accelerate/accelerator.py", line 1537, in _prepare_deepspeed
x1000c0s6b0n0:     engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/__init__.py", line 165, in initialize
x1000c0s6b0n0:     engine = DeepSpeedEngine(args=args,
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 309, in __init__
x1000c0s6b0n0:     self._configure_optimizer(optimizer, model_parameters)
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1173, in _configure_optimizer
x1000c0s6b0n0:     basic_optimizer = self._configure_basic_optimizer(model_parameters)
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1229, in _configure_basic_optimizer
x1000c0s6b0n0:     optimizer = DeepSpeedCPUAdam(model_parameters,
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
x1000c0s6b0n0:     self.ds_opt_adam = CPUAdamBuilder().load()
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 454, in load
x1000c0s6b0n0:     return self.jit_load(verbose)
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 497, in jit_load
x1000c0s6b0n0:     op_module = load(name=self.name,
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
x1000c0s6b0n0:     return _jit_compile(
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
x1000c0s6b0n0:     _write_ninja_file_and_build_library(
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1592, in _write_ninja_file_and_build_library
x1000c0s6b0n0:     verify_ninja_availability()
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1648, in verify_ninja_availability
x1000c0s6b0n0:     raise RuntimeError("Ninja is required to load C++ extensions")
x1000c0s6b0n0: RuntimeError: Ninja is required to load C++ extensions
x1000c1s1b0n0: Loading extension module cpu_adam...
x1000c1s1b0n0: Time to load cpu_adam op: 0.502467155456543 seconds
x1000c1s1b0n0: Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f42085dca60>
x1000c1s1b0n0: Traceback (most recent call last):
x1000c1s1b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
x1000c1s1b0n0:     self.ds_opt_adam.destroy_adam(self.opt_id)
x1000c1s1b0n0: AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
x1000c0s6b0n0:  [WARNING]  cpu_adam cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!
x1000c0s6b0n0: Using /home/users/industry/dso/lannliat/.cache/torch_extensions/py310_cu116 as PyTorch extensions root...
x1000c0s6b0n0: Traceback (most recent call last):
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/transformers/examples/pytorch/language-modeling/run_clm.py", line 634, in <module>
x1000c0s6b0n0:     main()
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/transformers/examples/pytorch/language-modeling/run_clm.py", line 582, in main
x1000c0s6b0n0:     train_result = trainer.train(resume_from_checkpoint=checkpoint)
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/transformers/src/transformers/trainer.py", line 1539, in train
x1000c0s6b0n0:     return inner_training_loop(
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/transformers/src/transformers/trainer.py", line 1659, in _inner_training_loop
x1000c0s6b0n0:     model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/accelerate/accelerator.py", line 1198, in prepare
x1000c0s6b0n0:     result = self._prepare_deepspeed(*args)
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/accelerate/accelerator.py", line 1537, in _prepare_deepspeed
x1000c0s6b0n0:     engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/__init__.py", line 165, in initialize
x1000c0s6b0n0:     engine = DeepSpeedEngine(args=args,
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 309, in __init__
x1000c0s6b0n0:     self._configure_optimizer(optimizer, model_parameters)
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1173, in _configure_optimizer
x1000c0s6b0n0:     basic_optimizer = self._configure_basic_optimizer(model_parameters)
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1229, in _configure_basic_optimizer
x1000c0s6b0n0:     optimizer = DeepSpeedCPUAdam(model_parameters,
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
x1000c0s6b0n0:     self.ds_opt_adam = CPUAdamBuilder().load()
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 454, in load
x1000c0s6b0n0:     return self.jit_load(verbose)
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 497, in jit_load
x1000c0s6b0n0:     op_module = load(name=self.name,
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
x1000c0s6b0n0:     return _jit_compile(
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
x1000c0s6b0n0:     _write_ninja_file_and_build_library(
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1592, in _write_ninja_file_and_build_library
x1000c0s6b0n0:     verify_ninja_availability()
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1648, in verify_ninja_availability
x1000c0s6b0n0:     raise RuntimeError("Ninja is required to load C++ extensions")
x1000c0s6b0n0: RuntimeError: Ninja is required to load C++ extensions
x1000c0s6b0n0: Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7eff0daaca60>
x1000c0s6b0n0: Traceback (most recent call last):
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
x1000c0s6b0n0:     self.ds_opt_adam.destroy_adam(self.opt_id)
x1000c0s6b0n0: AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
x1000c0s6b0n0: Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f0145cb8a60>
x1000c0s6b0n0: Traceback (most recent call last):
x1000c0s6b0n0:   File "/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
x1000c0s6b0n0:     self.ds_opt_adam.destroy_adam(self.opt_id)
x1000c0s6b0n0: AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
x1000c1s1b0n0: [2023-07-16 11:24:04,470] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2431494
x1000c0s6b0n0: [2023-07-16 11:24:04,784] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 665498
x1000c0s6b0n0: [2023-07-16 11:24:04,804] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 665499
```

When I tried single node training, the training procedes smoothly:
```
deepspeed --num_gpus=2 $ROOT_DIR/transformers/examples/pytorch/language-modeling/run_clm.py \
    --model_name_or_path gpt2 \
    --dataset_name wikitext \
    --dataset_config_name wikitext-2-raw-v1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --do_train \
    --do_eval \
    --output_dir ~/scratch/finetuned_models/debug \
    --deepspeed "$ROOT_DIR/FastChat/fastchat/ds_config/ds_config_zero3.json"
```

**Expected behavior**

Expected training to proceed smoothly as in single node case.

**ds_report output**
```
[2023-07-16 11:49:51,645] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
CUDA SETUP: Loading binary /home/users/industry/dso/lannliat/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-devel package with yum
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
No CUDA runtime is found, using CUDA_HOME='/app/apps/cuda/11.6.2'
DeepSpeed general environment info:
torch install path ............... ['/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/torch']
torch version .................... 1.13.1
deepspeed install path ........... ['/home/users/industry/dso/lannliat/.conda/envs/debug/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.9.5, unknown, unknown
torch cuda version ............... 11.6
torch hip version ................ None
nvcc version ..................... 11.6
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.6
```
**Screenshots**

**System info (please complete the following information):**
 - OS: Red Hat Enterprise Linux 8.4 (Ootpa)
 - Two machines with 2xA100s (40gb) each
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version: 3.10.12
 - `conda list` output
```
# packages in environment at /home/users/industry/dso/lannliat/.conda/envs/debug:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
accelerate                0.21.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
blas                      1.0                         mkl  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.05.30           h06a4308_0  
cachetools                5.3.1                    pypi_0    pypi
certifi                   2023.5.7                 pypi_0    pypi
charset-normalizer        3.2.0                    pypi_0    pypi
click                     8.1.5                    pypi_0    pypi
cuda                      11.6.1                        0    nvidia
cuda-cccl                 11.6.55              hf6102b2_0    nvidia
cuda-command-line-tools   11.6.2                        0    nvidia
cuda-compiler             11.6.2                        0    nvidia
cuda-cudart               11.6.55              he381448_0    nvidia
cuda-cudart-dev           11.6.55              h42ad0f4_0    nvidia
cuda-cuobjdump            11.6.124             h2eeebcb_0    nvidia
cuda-cupti                11.6.124             h86345e5_0    nvidia
cuda-cuxxfilt             11.6.124             hecbf4f6_0    nvidia
cuda-driver-dev           11.6.55                       0    nvidia
cuda-gdb                  12.2.53                       0    nvidia
cuda-libraries            11.6.1                        0    nvidia
cuda-libraries-dev        11.6.1                        0    nvidia
cuda-memcheck             11.8.86                       0    nvidia
cuda-nsight               12.2.53                       0    nvidia
cuda-nsight-compute       12.2.0                        0    nvidia
cuda-nvcc                 11.6.124             hbba6d2d_0    nvidia
cuda-nvdisasm             12.2.53                       0    nvidia
cuda-nvml-dev             11.6.55              haa9ef22_0    nvidia
cuda-nvprof               12.2.60                       0    nvidia
cuda-nvprune              11.6.124             he22ec0a_0    nvidia
cuda-nvrtc                11.6.124             h020bade_0    nvidia
cuda-nvrtc-dev            11.6.124             h249d397_0    nvidia
cuda-nvtx                 11.6.124             h0630a44_0    nvidia
cuda-nvvp                 12.2.60                       0    nvidia
cuda-runtime              11.6.1                        0    nvidia
cuda-samples              11.6.101             h8efea70_0    nvidia
cuda-sanitizer-api        12.2.53                       0    nvidia
cuda-toolkit              11.6.1                        0    nvidia
cuda-tools                11.6.1                        0    nvidia
cuda-visual-tools         11.6.1                        0    nvidia
datasets                  2.13.1                   pypi_0    pypi
deepspeed                 0.9.5                    pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
evaluate                  0.4.0                    pypi_0    pypi
exceptiongroup            1.1.2                    pypi_0    pypi
filelock                  3.12.2                   pypi_0    pypi
frozenlist                1.4.0                    pypi_0    pypi
gds-tools                 1.7.0.149                     0    nvidia
google                    3.0.0                    pypi_0    pypi
google-api-core           2.11.1                   pypi_0    pypi
google-api-python-client  2.93.0                   pypi_0    pypi
google-auth               2.22.0                   pypi_0    pypi
google-auth-httplib2      0.1.0                    pypi_0    pypi
googleapis-common-protos  1.59.1                   pypi_0    pypi
httplib2                  0.22.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46305  
joblib                    1.3.1                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libcublas                 11.9.2.110           h5e84587_0    nvidia
libcublas-dev             11.9.2.110           h5c901ab_0    nvidia
libcufft                  10.7.1.112           hf425ae0_0    nvidia
libcufft-dev              10.7.1.112           ha5ce4c0_0    nvidia
libcufile                 1.7.0.149                     0    nvidia
libcufile-dev             1.7.0.149                     0    nvidia
libcurand                 10.3.3.53                     0    nvidia
libcurand-dev             10.3.3.53                     0    nvidia
libcusolver               11.3.4.124           h33c3c4e_0    nvidia
libcusparse               11.7.2.124           h7538f96_0    nvidia
libcusparse-dev           11.7.2.124           hbbe9722_0    nvidia
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libnpp                    11.6.3.124           hd2722f0_0    nvidia
libnpp-dev                11.6.3.124           h3c42840_0    nvidia
libnvjpeg                 11.6.2.124           hd473ad6_0    nvidia
libnvjpeg-dev             11.6.2.124           hb5906b9_0    nvidia
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
mkl                       2023.1.0         h6d00ec8_46342  
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
ninja                     1.11.1                   pypi_0    pypi
nsight-compute            2023.2.0.16                   0    nvidia
numpy                     1.25.1                   pypi_0    pypi
openssl                   3.0.9                h7f8727e_0  
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pip                       23.1.2          py310h06a4308_0  
pluggy                    1.2.0                    pypi_0    pypi
protobuf                  4.23.4                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pyarrow                   12.0.1                   pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pydantic                  1.10.11                  pypi_0    pypi
pyparsing                 3.1.0                    pypi_0    pypi
pytest                    7.4.0                    pypi_0    pypi
python                    3.10.12              h955ad1f_0  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.13.1          py3.10_cuda11.6_cudnn8.3.2_0    pytorch
pytorch-cuda              11.6                 h867d48c_1    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.31.0                   pypi_0    pypi
responses                 0.18.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-learn              1.3.0                    pypi_0    pypi
scipy                     1.11.1                   pypi_0    pypi
setuptools                67.8.0          py310h06a4308_0  
six                       1.16.0                   pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tbb                       2021.8.0             hdb19cb5_0  
threadpoolctl             3.2.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1                    pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.31.0.dev0              pypi_0    pypi
typing_extensions         4.6.3           py310h06a4308_0  
tzdata                    2023.3                   pypi_0    pypi
uritemplate               4.1.1                    pypi_0    pypi
urllib3                   1.26.16                  pypi_0    pypi
wheel                     0.38.4          py310h06a4308_0  
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0  
yarl                      1.9.2                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
```

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?
Using `deepspeed` launcher

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by loadams** [comment]
@larrylawl - this looks like the same thing as issue #4257 - could you see if you see something similar to that error in your logs?  Or share the full log?

**Comment by larrylawl** [comment]
Hi, thanks for getting back to me. The issue is fixed when I used the pytorch-nvidia container v22.04 ((https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-04.html#rel_22-04)) and latest deepspeed package .

**Comment by circlecrystal** [comment]
For anyone still encountered the same error, please refer to my solution in https://github.com/microsoft/DeepSpeed/issues/1687

**Comment by liangxhao** [comment]
+1
